[build]
builder = "DOCKERFILE"

[deploy]
restartPolicyType = "ON_FAILURE"
# Força a Railway a rodar o script (Ignora se o Dockerfile falhar)
startCommand = "sh /start.sh"
# Força a Railway a procurar a saúde na rota correta
healthcheckPath = "/?health"

[volumes.data]
mountPath = "/data"